version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql-server-container
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrong!Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql
    networks:
      - app-network
    restart: always

  backend:
    build:
      context: ./backend
    container_name: backend-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=ProductDatabase;User=sa;Password=yourStrong!Passw0rd;
    ports:
      - "5235:80"  # Porta do backend
    depends_on:
      - db
    networks:
      - app-network
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: react-frontend
    ports:
      - "3000:80"  # Porta do frontend
    networks:
      - app-network
    restart: always

volumes:
  sql-data:

networks:
  app-network:
    driver: bridge
